### ISSUE TITLE
Bug: after delete on macro scene sg magnet option doesnt come up

### ISSUE THREAD

**Issue by aaronpostus** [game-based-learning/stern-gerlach-sim#25]

**Comment by joshvarg** [comment]
**:warning:Though functional bug needs to be revisited for a more robust solution under future refactor.:warning:**
# Intended Behaviour

In the classical magnet scene, we are checking the number of magnets (0 or 1). This is done in order to correctly display the option of placing an S-G Magnet on an empty node if there are 0 SGMs or *not* displaying the option if there is 1.

# Bug

The button would correctly disappear after placing the first magnet but after pressing the delete button, and then trying to place an SGM again, the button would no longer show up, which is an incorrect behaviour.

# Solution

In original implementation, `UIUpdater.DeleteButtonPressed()` (the method attached to the delete button) will check if the object deleted has a specific name. The issue was that the name was an outdated name and needed to be updated.

For the fix I switched to the current name of the object/prefab of the SGM.
